/* eslint-disable react/no-unescaped-entities */
import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillGithub,
  AiFillLinkedin,
  AiFillFileText,
  FiMapPin,
} from "react-icons/ai";

import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";

const grayGradient = "bg-gradient-to-b from-gray-200 to-gray-600";
const paddingAndRadius = "px-4 py-2 rounded-lg";
const darkStyles = "dark:bg-gray-800 dark:text-white";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Kobys Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*  Start of Page */}
      <main className={`px-10 bg-gray-200 text-black pb-20 md:px-20 lg:px-40 ${darkStyles}`}>
        {/* Navbar */}
        <section>
          <nav className="mb-12 p-6 pt-10 flex justify-center bg-white rounded-b-lg">
            <ul className="flex items-center">
              <li className="px-4">
                <a href="#home">Home</a>
              </li>
              <li className="px-4">
                <a href="#background">Background</a>
              </li>
              <li className="px-4">
                <a href="#portfolio">Portfolio</a>
              </li>
              <li className="px-4">
                < BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
            </ul>
          </nav>
        </section>
        <section
          id="home"
          className="bg-purple-200 min-h-screen shadow-lg rounded-lg"
        >
          {/* Info */}
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-purple-500 font-medium md:text-6xl ">
              Koby Sillito
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl">Full Stack Developer</h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto">
              Hi, I'm Koby, a full stack developer from the US. I'm currently
              studying at the University of Texas, and I'm looking for a
              placement.
            </p>
          </div>
          {/* Socials */}
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <a href="https://github.com/KobyS82" TARGET="_blank">
              <AiFillGithub />
            </a>
            <a
              href="#https://www.linkedin.com/in/koby-sillito/"
              TARGET="_blank"
            >
              <AiFillLinkedin />
            </a>
            <a
              href="#https://docs.google.com/document/d/17N3A6zOqL7IJ6HCXbcePu9OvhL8HGvxpBMXVfIZhKWc/edit?usp=sharing"
              TARGET="_blank"
            >
              <AiFillFileText />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-pink-300 to-indigo-200 rounded-full w-80 h-80 m-20 overflow-hidden md:h-96 md:w-96">
            <Image src={deved} alt="dev ed" layout="fill" objectFit="cover" />
          </div>
        </section>

        {/* Background */}
        <section id="background">
          <div className="bg-">
            <h3 className="text-3xl py-1">Background</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam
              <span className="text-teal-500"> voluptate</span> quod quia quas a
              at <span className="text-teal-500">voluptate</span> quod quia quas
              a at.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800">
              I offer a wide range of services, from web development to
            </p>
          </div>
          <div className="lg:flex gap-10 ">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-indigo-200 dark:bg-white">
              <div className="flex justify-center">
                <Image src={design} alt="3d-design" width={100} height={100} />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Quisquam
              </p>
              <h4 className="py-4 text-teal-600">Dessign tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-indigo-200 dark:bg-white">
              <div className="flex justify-center">
                <Image src={code} alt="3d-design" width={100} height={100} />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Quisquam
              </p>
              <h4 className="py-4 text-teal-600">Dessign tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-indigo-200 dark:bg-white">
              <div className="flex justify-center">
                <Image
                  src={consulting}
                  alt="3d-design"
                  width={100}
                  height={100}
                />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Quisquam
              </p>
              <h4 className="py-4 text-teal-600">Dessign tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
          </div>
        </section>

        {/* Portfolio */}
        <section id="portfolio">
          <div>
            <h3 className="text-3xl py-1">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam
              <span className="text-teal-500"> voluptate</span> quod quia quas a
              at <span className="text-teal-500">voluptate</span> quod quia quas
              a at.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800">
              I offer a wide range of services, from web development to
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                src={web1}
                alt="Nike"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web2}
                alt="Nike"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web3}
                alt="Nike"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web4}
                alt="Nike"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web5}
                alt="Nike"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web6}
                alt="Nike"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
