import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";

const grayGradient = "bg-gradient-to-b from-gray-200 to-gray-600";
const paddingAndRadius = "px-4 py-2 rounded-lg";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Kobys Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 text-black">
        <section className="min-h-screen">
          {/* Navbar */}
          <nav className="py-10 mb-12 flex justify-between">
            <h1
              className={`text-xl font-burtons ${grayGradient} ${paddingAndRadius} `}
            >
              KobyS
            </h1>
            <ul className="flex items-center">
              <li className="px-4">Home</li>
              <li className="px-4">Projects</li>
              <li className="px-4">
                <BsFillMoonStarsFill className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className={`${grayGradient} text-white ${paddingAndRadius}`}
                  href="#"
                >
                  Resume
                </a>
              </li>
              <li className="px-4">GitHub</li>
            </ul>
          </nav>
          {/* Info */}
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">Koby Sillito</h2>
            <h3 className="text-2xl py-2">Full Stack Developer</h3>
            <p className="text-md py-5 leading-8 text-gray-800">
              Hi, I'm Koby, a full stack developer from the US. I'm currently
              studying at the University of Texas, and I'm looking for a
              placement.
            </p>
          </div>
          {/* Socials */}
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div>

          </div>
        </section>
      </main>
    </div>
  );
}
